### ISSUE TITLE
V1.38 Windows Defender virus detection

### ISSUE THREAD

**Issue by Neurrone** [DavidKinder/Git#19]
Windows Defender is flagging the binary as a virus.

[Virustotal scan results](https://www.virustotal.com/gui/file/5b489c671f8d52d5a33e95e27b8dc4b3de069058975637e9f6e3ad01c1f09c48?nocache=1)

**Comment by DavidKinder** [comment]
This has happened before, see for example https://github.com/DavidKinder/Git/issues/11, and also discussion here: https://intfiction.org/t/avg-blocks-git-exe-because-its-infected-with-malware/51294

In the past reporting this to Windows Defender as a false positive has made the report go away, at least for a while, but then it comes back.
