### ISSUE TITLE
Windows Defender flags the latest version as malicious

### ISSUE THREAD

**Issue by leafcathead** [DavidKinder/Git#20]
The latest executable (Git 1.3.8) Here is the analysis from VirusTotal: https://www.virustotal.com/gui/file/5b489c671f8d52d5a33e95e27b8dc4b3de069058975637e9f6e3ad01c1f09c48/detection

Malwarebytes also flagged the file as suspicious.

**Comment by DavidKinder** [comment]
This has happened before, see for example https://github.com/DavidKinder/Git/issues/11, https://github.com/DavidKinder/Git/issues/19, and also discussion here: https://intfiction.org/t/avg-blocks-git-exe-because-its-infected-with-malware/51294

Note that most of the VirusTotal reports are some sort of "generic" or "heuristic" detection. In the past reporting this to a few AV companies as a false positive has made the report go away, at least for a while, but then it comes back.
